"""
routes/dev.py
-------------
Developer utilities and testing endpoints.
⚠️ FOR DEVELOPMENT AND DEMO PURPOSES ONLY ⚠️
"""

import uuid
from datetime import date, timedelta
from typing import List
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from pydantic import BaseModel

from app.database import get_db
from app.models.crop_models import CropSeason, FarmingAction
from app.engine import run_engine
from app.timeline import build_timeline
from app.routes.seasons import estimate_harvest_date

router = APIRouter(prefix="/dev", tags=["Developer Tools"])

# ── Per-crop limits & schedules ────────────────────────────────────────────────
CROP_MAX_IRRIGATIONS_PER_WEEK: dict[str, int] = {
    "wheat": 1, "rice": 3, "maize": 1, "tomato": 2,
}
CROP_IRRIGATION_INTERVALS: dict[str, int] = {
    "wheat": 10, "rice": 3, "maize": 7, "tomato": 4,
}


# ── Request models ─────────────────────────────────────────────────────────────

class WeeklyLog(BaseModel):
    week: int                        # week number starting from 1
    irrigations_done: int = 0        # how many irrigations done this week
    fertilizer_done: bool = False
    weeding_done: bool = False
    pesticide_done: bool = False
    fungicide_done: bool = False
    health_observation: bool = False


class TestSeasonRequest(BaseModel):
    crop_name: str
    days_since_sowing: int
    # Farm details (stored in season notes)
    soil_type: str = "loamy"
    region: str = "north_india"
    season: str = "rabi"
    # Weekly farming log
    weekly_log: List[WeeklyLog] = []


# ── Endpoint ───────────────────────────────────────────────────────────────────

@router.post("/generate-test-season", summary="[DEV] Generate a test season from a weekly farming log")
def generate_test_season(data: TestSeasonRequest, db: Session = Depends(get_db)):
    """
    ⚠️ FOR DEVELOPMENT AND DEMO PURPOSES ONLY ⚠️

    Creates a crop season backdated by `days_since_sowing`, processes each week
    of the provided farming log into real FarmingAction rows, then runs the
    recommendation engine and timeline builder and returns everything in one payload.
    """
    # 1. Sowing date
    sowing_date_obj = date.today() - timedelta(days=data.days_since_sowing)
    sowing_date_str = sowing_date_obj.isoformat()
    harvest_date = estimate_harvest_date(data.crop_name, sowing_date_str)
    season_id = str(uuid.uuid4())
    crop_key = data.crop_name.strip().lower()
    today_str = date.today().isoformat()

    # 2. Create season
    season = CropSeason(
        season_id=season_id,
        field_id="dev-test-field",
        farmer_id="dev-test-farmer",
        crop_name=data.crop_name.strip().title(),
        crop_variety="Test Variety",
        sowing_date=sowing_date_str,
        expected_harvest_date=harvest_date,
        current_stage="SOWING",
        status="ACTIVE",
        notes=(
            f"Generated by test endpoint | "
            f"Soil: {data.soil_type} | Region: {data.region} | Season: {data.season}"
        ),
    )
    db.add(season)

    simulated_actions: list[str] = []
    warnings: list[str] = []
    max_irr = CROP_MAX_IRRIGATIONS_PER_WEEK.get(crop_key, 1)

    # Gather single-event flags across all weeks
    has_fert = any(e.fertilizer_done for e in data.weekly_log)
    has_weed = any(e.weeding_done for e in data.weekly_log)
    has_pest = any(e.pesticide_done for e in data.weekly_log)
    has_fung = any(e.fungicide_done for e in data.weekly_log)
    has_obs  = any(e.health_observation for e in data.weekly_log)

    # 3. Process weekly log for irrigations
    for entry in data.weekly_log:
        w = entry.week
        week_start_day = (w - 1) * 7
        week_start_date = sowing_date_obj + timedelta(days=week_start_day)

        # Cap irrigations
        irr_count = entry.irrigations_done
        if irr_count > max_irr:
            warnings.append(
                f"Week {w}: {irr_count} irrigations requested, capped at {max_irr} for {crop_key}."
            )
            irr_count = max_irr

        # Spread N irrigations evenly across 7-day window
        for i in range(irr_count):
            day_offset = int((i + 1) * 7 / (irr_count + 1))
            irr_date = (week_start_date + timedelta(days=day_offset)).isoformat()
            if irr_date <= today_str:
                db.add(FarmingAction(
                    action_id=str(uuid.uuid4()),
                    season_id=season_id,
                    farmer_id="dev-test-farmer",
                    action_type="IRRIGATION",
                    action_date=irr_date,
                    notes=f"Week {w} irrigation ({i + 1}/{irr_count})",
                    is_synced=True,
                ))
                if "IRRIGATION" not in simulated_actions:
                    simulated_actions.append("IRRIGATION")

    # Log single events on their agronomic milestone days
    pest_days = {"wheat": 45, "rice": 35, "maize": 30, "tomato": 35}
    fung_days = {"wheat": 60, "rice": 60, "maize": 50, "tomato": 45}

    single_events = [
        (has_fert, "FERTILIZER_APPLICATION", 21, "Fertilizer applied"),
        (has_weed, "WEEDING",                21, "Weeding done"),
        (has_obs,  "HEALTH_OBSERVATION",     10, "Early check"),
        (has_pest, "PESTICIDE_SPRAY",        pest_days.get(crop_key, 35), "Pesticide spray"),
        (has_fung, "FUNGICIDE_SPRAY",        fung_days.get(crop_key, 50), "Fungicide spray"),
    ]

    for flag, action_type, target_day, label in single_events:
        if flag:
            target_date = (sowing_date_obj + timedelta(days=target_day)).isoformat()
            if target_date <= today_str:
                db.add(FarmingAction(
                    action_id=str(uuid.uuid4()),
                    season_id=season_id,
                    farmer_id="dev-test-farmer",
                    action_type=action_type,
                    action_date=target_date,
                    notes=f"Simulated {label} (Day {target_day})",
                    is_synced=True,
                ))
                if action_type not in simulated_actions:
                    simulated_actions.append(action_type)

    db.commit()
    db.refresh(season)

    # 4. Recommendation engine (also auto-updates stage)
    engine_result = run_engine(season, db)
    db.refresh(season)

    # 5. Timeline
    timeline = build_timeline(season, db)

    return {
        "message": "Test season created successfully",
        "crop_name": season.crop_name,
        "season_id": season.season_id,
        "days_since_sowing": engine_result["days_since_sowing"],
        "detected_stage": engine_result["current_stage"],
        "crop_health_score": engine_result["crop_health_score"],
        "health_status": engine_result["health_status"],
        "score_details": engine_result["score_details"],
        "simulated_actions": simulated_actions,
        "warnings": warnings,
        "recommendations": engine_result["recommendations"],
        "timeline": timeline,
    }
